### ISSUE TITLE
GUI shows not the latest gamestate, but the penultimate one (when stepping)

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#1]
If the game is paused and stepping in the GUI is used, only the penultimate GameState is shown. That's because the newest gamestate is not send to clients (also the GUI is a client) when the game is paused, so that clients can't start calculations before they get a move request.

Solution is is here obviously to send the gamestate to priviliged observers (the gui can authenticate itself), even if the game is paused.

**Comment by SKoschnicke** [comment]
https://github.com/CAU-Kiel-Tech-Inf/server/blob/f6981112be66e18d0ba07c3782fbf5eacf5784e3/socha-sdk/src/server-api/sc/framework/plugins/RoundBasedGameInstance.java#L167

**Comment by Yasamato** [comment]
#5 Is this related?

**Comment by anarchuser** [comment]
quite possibly so.
I haven't been able to check further

**Comment by Yasamato** [comment]
#5 was not related

**Comment by SKoschnicke** [comment]
@anarchuser this has to be implemented in the server, see my code reference and explaination above.

**Comment by anarchuser** [comment]
Yes, we need something like `notifyObserverOnNewState` to only notify the observers. I'll look into it

**Comment by anarchuser** [comment]
https://github.com/CAU-Kiel-Tech-Inf/backend/pull/293 should fix this
