### ISSUE TITLE
Support for manually started clients

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#18]
When the user wants to start a game with a client which should not be started by the GUI directly but e.g. from an IDE, the GUI has to create a game without reservations and wait for the external client to join (displaying a message to the user that the client shoud now be started) and then joining the second player (in case the first player is manually startet) *or* joining the first player and then waiting (in case the second player is manually starting) *or* waiting until both manually started players are joined. This is because without reservations we can't determine which client joins in which slot of the game. The first client which joins always gets the first slot.

**Comment by xerus2000** [comment]
In the long term we might consider adding an option to request either first or second slot
