### ISSUE TITLE
Game window is still not small enough

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#25]
Seems that in a maximized game window the content is cropped at the bottom because of the space the task bar occupies:
![image](https://user-images.githubusercontent.com/105162/94125388-8fb70400-fe56-11ea-8594-78db934ef9ec.png)
![image](https://user-images.githubusercontent.com/105162/94125420-9c3b5c80-fe56-11ea-9d62-25510923612f.png)

**Comment by xerus2000** [comment]
Isn't that an issue of the OS? That should prevent maximized windows from going under the task bar, no?

**Comment by SKoschnicke** [comment]
I think the window content is cropped, not under the taskbar.

**Comment by xerus2000** [comment]
![image](https://user-images.githubusercontent.com/13354331/97713882-b2c17d00-1ac0-11eb-8e98-0777cb2d1a8a.png)

**Comment by SKoschnicke** [comment]
Might be solved already with the new "Passen" button

**Comment by SKoschnicke** [comment]
![image](https://user-images.githubusercontent.com/105162/97715127-4c3d5e80-1ac2-11eb-8fba-e503f877ab56.png)

Still problems with scaling. Got this when I started fullscreen (4K) and resized down to about 1/4 screen

**Comment by SKoschnicke** [comment]
Chosen piece graphic was rescaled properly when I changed the chosen piece, though.

**Comment by xerus2000** [comment]
I guess this is fixed by now?
