### ISSUE TITLE
Show current round instead of current turn

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#27]
Because we have a round limit, this information is important to the player.

**Comment by SKoschnicke** [comment]
Also, the turn-count can confuse the user. If a color can't place a piece anymore, it is skipped and that doesn't count as turn anymore. So rounds have fewer turns in the later game and the sum of turns can be less than 25 * 4.

@anarchuser is there a way to get the current round? Seems like it can't be calculated from the current turn.

**Comment by anarchuser** [comment]
GameState has a `round` property which keeps track of the current round
