### ISSUE TITLE
"Play" and "Pause" Button text in english

### ISSUE THREAD

**Issue by anarchuser** [CAU-Kiel-Tech-Inf/gui#31]
For consistency, everything should be in German.
Esp. since it says "Drücke auf Start" it seems weird that the "start" button is labelled "Play"

**Comment by xerus2000** [comment]
Seems already fixed

**Comment by xerus2000** [comment]
nvm, misread

**Comment by anarchuser** [comment]
Now it always says "Weiter", which works after pausing a game.
However, while actually starting the game, "Weiter" seems misplaced (as you don't _continue_ the game)

**Comment by anarchuser** [comment]
![Screenshot_20201005_121200](https://user-images.githubusercontent.com/5949896/95067348-fca68580-0703-11eb-8d8c-0d9e6816d2e7.png)

**Comment by anarchuser** [comment]
![Screenshot_20201005_121236](https://user-images.githubusercontent.com/5949896/95067380-1051ec00-0704-11eb-9464-b96be1766fc8.png)

**Comment by xerus2000** [comment]
woops
