### ISSUE TITLE
Don't rotate pieces in undeployed pieces view or fix problems with rotation there

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#32]
![image](https://user-images.githubusercontent.com/105162/94127859-b9bdf580-fe59-11ea-92b8-0b6215785c4d.png)

**Comment by anarchuser** [comment]
Duplicate of https://github.com/CAU-Kiel-Tech-Inf/gui/issues/10
It seems this is caused by flipping the image

**Comment by SKoschnicke** [comment]
Duplicate of #10
