### ISSUE TITLE
Clear complete state when starting a new game after one already played

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#36]
When using the "New Game" option while already in a game, it seems that the state is not completely reset:
- The board is empty, but hovering with a piece behaves as if there are already pieces on the board (piece turns black on empty fields)
- The Play/Pause button stays in "Pause" state

After pressing the "Pause" button, the new game seems to be started and overwrites all state, so that the game can be played properly, but it is irritating nonetheless.

**Comment by SKoschnicke** [comment]
I think that should be addressed with priority as it might confuse users and lead to hard to analyze bug reports.

**Comment by xerus2000** [comment]
Had an even more grave issue just now: The previous game (CvC) continued in the background, then I got a game ended message even though my field was empty, and clicking on "Weiter" terminated the game and brought me back to the welcome-screen.

**Comment by xerus2000** [comment]
Should be fixed by https://github.com/CAU-Kiel-Tech-Inf/gui/commit/a762fea63f18742577d817eed04aa36f7b1396a1
