### ISSUE TITLE
Wrong score shown after last turn

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#38]
It seems that after the move which ends the game, the score display is not updated showing the final score.

Below is a screenshot of such case, yellow placed all pieces, but didnt end with the monomino, green also placed all pieces and the monomino as last piece, which should have increased the score of team two by 16 (1+10+5) to 208.

![image](https://user-images.githubusercontent.com/105162/95661766-2e6b8200-0b32-11eb-80c1-c8800a773d5b.png)

Observed with GUI version 21.0.6

**Comment by anarchuser** [comment]
weirdly, the final score should be 213, so there are points missing somewhere else too

**Comment by anarchuser** [comment]
I can't reproduce this; for me it works flawlessly:
![image](https://user-images.githubusercontent.com/5949896/96575938-b50e2500-12d1-11eb-8d23-cb761cba4377.png)

If this issue still persists for you, please reopen

**Comment by anarchuser** [comment]
Confirmed that this is present in the newest release but not on master

**Comment by xerus2000** [comment]
Kai: Ein weiteres Problem besteht darin, dass der letzte Zug nicht angezeigt wird und der angezeigte Punktestand nicht dem Endergebnis entspricht. In dem ersten Video bleibt Blue::MONO übrig, obwohl er als letzter Zug gesetzt wurde.

http://wollw.de/pus/sc21/GUI_Bug_end_of_game.mp4
In diesem Spiel wurden Blue::MONO und Red::MONO als letzte Steine gesetzt.

Coronon:  Das liegt nicht an der GUI, das gleiche Problem hatten wir auch mit unserer GUI Implementation, das Backend sendet das einfach nicht (Das ergebnis am Ende stimmt dann aber [Ist halt blöd für unsere Replay Implementation, über einen Fix würden wir uns also auch sehr freuen])

-> seems to be a backend issue

**Comment by xerus2000** [comment]
pretty sure this backend code of the game is at fault:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/13354331/104900345-426a1f80-597c-11eb-9ca6-6e712a2d5f85.png">

**Comment by xerus2000** [comment]
I can change this to send the new state before game over, but I'd like to also test it somehow...
