### ISSUE TITLE
Receiving </protocol> after SkipMove

### ISSUE THREAD

**Issue by niklasCarstensen** [CAU-Kiel-Tech-Inf/gui#39]
Ich packe das issue zur gui, weil es bei Interaktion mit dem gui server aufgetreten ist, aber es kann auch am backend liegen, oder auch an meinem Client, da der noch nicht ausreichend getestet wurde, aber die XML Kommunikation sieht meines Erachtens legitim aus.

Das Problem ist, dass Spieler TWO hier nach einem notwendigen SkipMove `</protocol>` erhält und leavt.
![image](https://user-images.githubusercontent.com/19777592/95684142-bc597280-0bef-11eb-8c78-857f91580304.png)

Gelb hat zu dem Zeitpunkt folgende Shapes
![image](https://user-images.githubusercontent.com/19777592/95684150-cda27f00-0bef-11eb-91d5-141632d608dd.png)

**Comment by anarchuser** [comment]
Was heißt "notwendiger SkipMove"?
Wenn keine SetMoves mehr möglich sind, sollten auch keine MoveRequests mehr gesendet werden.

**Comment by niklasCarstensen** [comment]
Letzteres könnte ich noch zur XML Doku hinzufügen.
Aber notwendig deshalb, weil es keine anderen legalen Züge für Gelb mehr gab und bei TWO, laut Logs, ein Request ankam.

Reden wir ggf. über verschiedene Server Versionen?

**Comment by anarchuser** [comment]
Der Server darf keine Requests schicken, wenn nur noch SkipMoves möglich sind.
Das hat bisher auch eigentlich immer funktioniert. 

Kannst du den Fehler reproduzieren und vollständige Logs schicken?

**Comment by niklasCarstensen** [comment]
Das sind die logs der beiden Spieler eines neuen runs.

[log-8585989078040518605.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5380079/log-8585989078040518605.txt)
[log-8585989078063974029.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5380080/log-8585989078063974029.txt)

Hier ist sonst auch der letzte Boardstate aufgemalt, vielleicht hilft das.

![board](https://user-images.githubusercontent.com/19777592/96029084-6d634580-0e5a-11eb-9346-f821f571e161.png)

**Comment by anarchuser** [comment]
In dem Fall kann Blau noch Züge tätigen.
Da wir in der GUI noch keine Möglichkeit hatten, SkipMoves zu testen, kann es gut sein, dass SkipMoves an sich das Problem sind

**Comment by anarchuser** [comment]
Besteht das Problem noch mit der neuesten Version?
Und wenn ja, funktioniert es mit [`fix/skipmoves`](https://github.com/CAU-Kiel-Tech-Inf/backend/tree/fix/skipmoves) anstatt master?

**Comment by niklasCarstensen** [comment]
Ich habe es gerade noch mal mit der Version 21.0.7 probiert und hatte ein ähnliches Log
[log-8585978750757957249.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5440264/log-8585978750757957249.txt)
[log-8585978751049294775.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5440265/log-8585978751049294775.txt)

Ich hab noch nie probiert die gui selbst zu bauen aber das kann ich später mal machen

**Comment by anarchuser** [comment]
* Bekommst du weiterhin MoveRequests, obwohl keine Moves möglich sind?
* Passiert das nach jedem SkipMove oder nur nach SkipMoves am Ende des Spiels?
* Hast du Server Logs?
* Hast du vielleicht einen Screenshot von dem Spielfeld?

**Comment by niklasCarstensen** [comment]
- Ja
- Mein SimpleClient sendet bisher nur SkipMoves wenn nichts mehr anderes möglich ist, weswegen es nur einmal am ende passiert.
- Wo legt der server die logs ab?
- Von dem alten run leider nicht mehr, aber ich könnte dir ein neues Beispiel mit gemaltem board geben

**Comment by anarchuser** [comment]
Wenn du den Server über eine Kommandozeile startest, sollte er einige Informationen ausgeben.

Aktuell sieht es so aus, als ob der Server einen MoveRequest ausgibt, obwohl das Spiel bereits zu Ende ist. Er scheint aber kein GameOver Event an die Clients zu senden.

**Comment by niklasCarstensen** [comment]
Okay ich habe einen weiteren run gemacht:
[log-8585977872876245536.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5446973/log-8585977872876245536.txt)
[log-8585977872843557541.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5446974/log-8585977872843557541.txt)
![board](https://user-images.githubusercontent.com/19777592/97338839-2164c780-1882-11eb-88c1-bb534254b2c3.png)

Das ist der ganze serverlog aus cmd:
[serverLog.txt](https://github.com/CAU-Kiel-Tech-Inf/gui/files/5446990/serverLog.txt)

Am interessantesten ist wohl der teil des serverlogs: 
```
18:26:57 WARN  sc.networking.clients.XStreamClient - Client sc.server.network.Client@741ed239 disconnected (Cause: LOST_CONNECTION, Exception: {})                                                      java.io.EOFException: null                                                                                  at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2075)                             at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)                                                                                      at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:484)                       at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)                       at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:99)                         at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)                                 at java.base/java.lang.Thread.run(Thread.java:834)                                          18:26:57 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:25 client:Client
```
![image](https://user-images.githubusercontent.com/19777592/97339169-8d473000-1882-11eb-9052-f909507a73c4.png)

**Comment by anarchuser** [comment]
Die interessante Zeile im Server Log ist die hier:
```18:26:57 WARN sc.server.network.Client - Packet null skipped wasn't processed.```
Ich hatte das in den Client Logs übersehen - wenn du SkipMoves sendest, sendest du keine Farbe mit.
Daher bekommt der Server einen SkipMove von Farbe `null`, womit er nichts anfangen kann.

Wenn du den SkipMove als
```
<data class="sc.plugin2021.SkipMove">
  <color>COLOR</color>
</data>
```
sendest, sollte es funktionieren.

**Comment by anarchuser** [comment]
Man sieht außerdem
```18:26:57 INFO sc.plugin2021.GameState - Removing YELLOW from the game```
dass der Server erkannt hat, dass GELB keine Züge mehr möglich hatte.

Warum dennoch ein MoveRequest gesendet wurde, muss ich mir nochmal gesondert anschauen

**Comment by anarchuser** [comment]
Tritt der Fehler noch auf?
Inzwischen gab es einige Änderungen, u.a. an SkipMoves

**Comment by xerus2000** [comment]
Ich schließe das dann erstmal
