### ISSUE TITLE
Unify Pass- and Pause-Button

### ISSUE THREAD

**Issue by xerus2000** [CAU-Kiel-Tech-Inf/gui#50]
Since the pass-button can only be used when its the turn of a human player, and there's no use pausing at that time, we can replace the buttons instead of adding an additional one. This conveniently hides the pause-button completely in a PvP game, where it is useless anyways.

Depends on #11 and appropriate autostart for humans.

**Comment by SKoschnicke** [comment]
Does this also work with the Back/Forward feature?

**Comment by xerus2000** [comment]
WDYM?

**Comment by SKoschnicke** [comment]
You can go back to an earlier gamestate. It seemed to me that the game is paused if you do that. If the Pause/Continue button is not there, you can't unpause such a game again.

**Comment by SKoschnicke** [comment]
But I'm not sure, just check if that is not a problem.

**Comment by xerus2000** [comment]
That is exactly the point: As soon as you go back in time, the pass-button can be replaced by the play/pause-button again - there is afaik no valid use-case where both are useful.
