### ISSUE TITLE
End-Screen

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/gui#7]
When a game ends, there should be a message displayed with the reason why the game ended and the scores.

**Comment by xerus2000** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/13354331/97973558-8cecee80-1dc6-11eb-93d0-b7688306ec8b.png">
There should be a newline instead of a comma

**Comment by anarchuser** [comment]
How about a transparent banner laying over the board, giving enough space for winner, score and reason?

**Comment by xerus2000** [comment]
I vehemently opposed that already. There is enough space at the top, and I want the board to stay fully visible.

**Comment by anarchuser** [comment]
Suggestion:
![image](https://user-images.githubusercontent.com/5949896/97976776-6e3d2680-1dcb-11eb-9d3a-5d5f99b7dc35.png)

**Comment by xerus2000** [comment]
Yep, that's essentially what I imagined.
Maybe add some padding between text and field, and please center the text horizontally

**Comment by SKoschnicke** [comment]
Great! Shouldn't we make it clearer that the game ended not regularly if a reason was given? Something like "Regelverletzung durch X!" or "X hat das Spiel vorzeitig verlassen!".
And (maybe as a second step, shouldn't block this feature) translate the reason messages to german.

**Comment by anarchuser** [comment]
It seems GameResult doesn't carry information on potential rule violators.
Thus I'll leave this information out for now (people can infer it from who's the winner), and maybe at a later point we can refactor GameResult to carry this information.

**Comment by anarchuser** [comment]
Furthermore, PlayerScores don't carry precise information on the reason except for the `reason`, a string property.
Unless we want to parse our own error messages, we can't provide as precise information as by simply printing the `reason` - above example'd look like this:
![image](https://user-images.githubusercontent.com/5949896/97979107-e527ee80-1dce-11eb-9da7-04c302860840.png)

**Comment by xerus2000** [comment]
Yeah we need to properly put the different violations into enums and stuff. Also Java has some way of localization that we should employ.

**Comment by anarchuser** [comment]
Well, we kind of have a proper enum already, with [`MoveMistake`](https://github.com/CAU-Kiel-Tech-Inf/backend/blob/ead80d5bba186e9d13e5d1f4a13da50b14309f25/plugin/src/shared/sc/plugin2021/util/MoveException.kt)s

**Comment by xerus2000** [comment]
Oh nice, wasn't aware of that yet!
Yes, seems sensible to include that in the GameResult rather than creating a host of new messages.
